# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for skipjack configurations
Name: jolla-configuration-skipjack
Requires:
- pattern:jolla-hw-adaptation-skipjack

- patterns-sailfish-applications
- patterns-sailfish-ui
# Early stages of porting benefit from these:
- pattern:sailfish-porter-tools

- sailfish-content-graphics-z@ICON_RES@

# Introduced starting Sailfish OS 2.0.4.x:
# 3rd party accounts like Twitter, VK, cloud services, etc
- jolla-settings-accounts-extensions-3rd-party-all

# Introduced starting Sailfish OS 2.1.1.26
# Required for Jolla Store Access
- patterns-sailfish-consumer-generic

# For Mozilla location services (online)
- geoclue-provider-mlsdb

# Sailfish OS CSD tool for hardware testing
# needs some configuration to get all features working
- csd

Summary: Jolla Configuration skipjack

